# action.yml
name: 'Azure Stack Hub Module Validation'
description: 'Checks modules for validation following the AzS Hub Doc Model.'
inputs:
  path:
    description: 'Source file or directory.'
    required: false
    default: "."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}