on: [pull_request]

jobs:
  azure-stack-hub-validation:
    runs-on: ubuntu-latest
    name: validate modules in Azure Stack Hub
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Azure Stack Hub Module Validation
      id: modulate-validation
      uses: actions/action-asz-validation@v1
    - name: Get the report text
    - run: echo "The report info is ${{ steps.hello.outputs.report }}"
