FROM python:3

ADD val_ki_dockeraction.py
ADD val_ki_functions.py
ADD mod_utilities.py
COPY known_issue.json /known_issue.json
COPY entrypoint.sh /entrypoint.sh
COPY requirements.txt /requirements.txt

pip install -r requirements.txt

ENTRYPOINT ["/entrypoint.sh"]